config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    collection do
      get :index_json
      get :export_pdf
    end
  end
  root "contacts#index"

  resources :countries do
    resources :departments, only: [:index]
  end

  resources :departments, only: [] do
    resources :cities, only: [:index]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :department
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :country
    belongs_to :department
    belongs_to :city

    validates :sex, presence: true
    validates :birth_date, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :address, presence: true
    validates :country_id, presence: true
    validates :department_id, presence: true
    validates :city_id, presence: true
    validates :information, presence: true

    validate :must_be_at_least_18_years_old
    validate :maximum_contacts_per_city

    private

    def must_be_at_least_18_years_old
      return if birth_date.blank?
  
      if birth_date > 18.years.ago.to_date
        errors.add(:birth_date, "Debes ser mayor de 18 años para contactarnos.")
      end
    end

    def maximum_contacts_per_city
        if Contact.where(city: city).count >= 3
          errors.add(:city, "Ya hay 3 registros en esta ciudad. No se pueden registrar más.")
        end
    end
    
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :departments
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    def index
      @cities = City.where(department_id: params[:department_id])
      respond_to do |format|
        format.json { render json: @cities }
      end
    end
  end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.includes(:country, :department, :city).all
    @totals_by_city = Contact.group(:city).count
  end

  def index_json
    @contacts = Contact.all
    render json: @contacts
  end

  def export_pdf
    @contacts = Contact.includes(city: :department).all.group_by(&:city)

    respond_to do |format|
      format.pdf do
        pdf = Prawn::Document.new(page_size: 'TABLOID', page_layout: :landscape)

        pdf.text "Solicitudes de Contacto por Ciudad", size: 30, style: :bold
        pdf.move_down 20

        @contacts.each do |city, contacts|
          pdf.text "Ciudad: #{city.name}", size: 20, style: :bold
          pdf.move_down 10

          table_data = contact_data(contacts)
          pdf.table(table_data, header: true, width: pdf.bounds.width, cell_style: { inline_format: true }) do
            row(0).font_style = :bold
            row(0).background_color = 'cccccc'  # Cambia el color de fondo del encabezado si lo deseas
          end

          pdf.move_down 20  # Espacio entre tablas
        end

        send_data pdf.render, filename: "contactos.pdf", type: "application/pdf", disposition: "attachment"
      end
      format.html do
        redirect_to contacts_path, alert: 'Formato no soportado. Solo PDF disponible.'
      end
    end
  end

  # GET /contacts/1 or /contacts/1.json
  def show
    @contact = Contact.includes(:country, :department, :city).find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @countries = Country.all
    @departments = []
    @cities = []
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.includes(:country, :department, :city).find(params[:id])
    @countries = Country.all
    @departments = Department.where(country_id: @contact.country_id)
    @cities = City.where(department_id: @contact.department_id)
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @countries = Country.all
    @departments = Department.where(country_id: @contact.country_id)
    @cities = City.where(department_id: @contact.department_id)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:sex, :birth_date, :first_name, :last_name, :email, :address, :address_details, :country_id, :department_id, :city_id, :information)
    end

    def contact_data(contacts)
      header = ['Nombre', 'Apellido', 'Email', 'Dirección', 'Ciudad', 'Departamento', 'País']
      data = contacts.map do |contact|
        [
          contact.first_name,
          contact.last_name,
          contact.email,
          contact.address,
          contact.city.name,
          contact.city.department.name,
          contact.city.department.country.name 
        ]
      end
      [header] + data
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    def show
      @country = Country.find(params[:id])
      @departments = @country.departments.includes(:cities) 
    end
  end
  

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    def index
      @departments = Department.where(country_id: params[:country_id])
      respond_to do |format|
        format.json { render json: @departments }
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Sex:</strong>
    <%= contact.sex %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= contact.birth_date %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= contact.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= contact.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= contact.address %>
  </p>

  <p>
    <strong>Address details:</strong>
    <%= contact.address_details %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= contact.country %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= contact.department %>
  </p>

  <p>
    <strong>City:</strong>
    <%= contact.city %>
  </p>

  <p>
    <strong>Information:</strong>
    <%= contact.information %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "problema") %> encontrados en el formulario:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sex, "Sexo", style: "display: block" %>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :birth_date, "Fecha de Nacimiento" %>
    <%= form.date_field :birth_date, min: (Date.today - 100.years).strftime("%Y-%m-%d"), max: (Date.today).strftime("%Y-%m-%d"), required: true %>
  </div>

  <div>
    <%= form.label :first_name, "Nombre", style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, "Apellido", style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, "Email", style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :address, "Dirección", style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :address_details, "Casa / Apartamento", style: "display: block" %>
    <%= form.text_field :address_details %>
  </div>
    
  <div class="field">
    <%= form.label :country_id %>
    <%= form.collection_select :country_id, @countries, :id, :name, { prompt: 'Selecciona un país' }, { id: 'country_select' } %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.collection_select :department_id, @departments, :id, :name, { prompt: 'Selecciona un departamento' }, { id: 'department_select' } %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.collection_select :city_id, @cities, :id, :name, { prompt: 'Selecciona una ciudad' }, { id: 'city_select' } %>
  </div>

  <div>
    <%= form.label :information, "Información", style: "display: block" %>
    <%= form.text_area :information %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editar Contacto</h1>

<div id="contact_form_container">

  <%= form_with(model: @contact, local: true, html: { id: "contact_form" }) do |form| %>
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "problema") %> encontrados en el formulario:</h2>

        <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="group_elements">
      <div class="field">
        <%= form.label :sex %>
        <%= form.select :sex, [['Masculino', 'masculino'], ['Femenino', 'femenino'], ['Otro', 'otro']] %>
      </div>

      <div class="field">
        <%= form.label :birth_date, "Fecha de Nacimiento" %>
        <%= form.date_field :birth_date, min: (Date.today - 100.years).strftime("%Y-%m-%d"), max: (Date.today).strftime("%Y-%m-%d"), required: true %>
      </div>

      <div class="field">
        <%= form.label :first_name, "Nombre" %>
        <%= form.text_field :first_name %>
      </div>

      <div class="field">
        <%= form.label :last_name,  "Apellido" %>
        <%= form.text_field :last_name %>
      </div>
    </div>

    <div class="field">
      <%= form.label :email, "Email"  %>
      <%= form.email_field :email %>
    </div>

    <div class="field">
      <%= form.label :address, "Dirección" %>
      <%= form.text_field :address %>
    </div>

    <div class="group_elements">

      <div class="field">
        <%= form.label :address_details,  "Casa / Apartamento"%>
        <%= form.text_area :address_details %>
      </div>

      <div class="field">
        <%= form.label :country_id %>
        <%= form.collection_select :country_id, @countries, :id, :name, { prompt: 'Selecciona un país' }, { id: 'country_select' } %>
      </div>

      <div class="field">
        <%= form.label :department_id %>
        <%= form.collection_select :department_id, @departments, :id, :name, { prompt: 'Selecciona un departamento' }, { id: 'department_select' } %>
      </div>

      <div class="field">
        <%= form.label :city_id %>
        <%= form.collection_select :city_id, @cities, :id, :name, { prompt: 'Selecciona una ciudad' }, { id: 'city_select' } %>
      </div>
    </div>
    <div class="field">
      <%= form.label :information, "Información" %>
      <%= form.text_area :information %>
    </div>

    <div class="content-actions">
      <%= form.submit "Guardar", class: "btn-submit" %>
    </div>
  <% end %>

</div>

app/views/contacts/index.html.erb
<h1>Registros de Contacto</h1>

<table class="contact-table">
  <thead>
    <tr>
      <th>Sexo</th>
      <th>Fecha de Nacimiento</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Dirección</th>
      <th>Detalles de Dirección</th>
      <th>País</th>
      <th>Departamento</th>
      <th>Ciudad</th>
      <th>Información</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.sex %></td>
        <td><%= contact.birth_date.strftime("%d/%m/%Y") %></td>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.address %></td>
        <td><%= contact.address_details %></td>
        <td><%= contact.country.name if contact.country.present? %></td>
        <td><%= contact.department.name if contact.department.present? %></td>
        <td><%= contact.city.name if contact.city.present? %></td>
        <td><%= contact.information %></td>
        <td class="content-actions">
          <%= link_to 'Mostrar', contact, class: "btn btn-show" %>
          <%= link_to 'Editar', edit_contact_path(contact), class: "btn btn-edit" %>
          <%= link_to 'Eliminar', contact, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Contactar', new_contact_path, class: "btn btn-add" %>
</div>

<h2>Total de Registros por Ciudad</h2>
<table class="city-totalization-table">
  <thead>
    <tr>
      <th>Ciudad</th>
      <th>Total Registros</th>
    </tr>
  </thead>
  <tbody>
    <% @totals_by_city.each do |city, count| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Acciones</h2>


<!-- Botón para ver contactos en JSON -->
<%= link_to "Ver en JSON", index_json_contacts_path, class: "btn btn-json", target: '_blank' %>

<!-- Botón para exportar a PDF -->
<%= link_to 'Exportar a PDF', export_pdf_contacts_path(format: :pdf), class: 'btn btn-pdf' %>

app/views/contacts/new.html.erb
<h1>Formulario de Contacto</h1>

<div id="contact_form_container">

<div id="about_us">
</div>
<%= form_with(model: @contact, local: true, html: { id: "contact_form" }) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "problema") %> encontrados en el formulario:</h2>

      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="group_elements">
    <div class="field">
      <%= form.label :sex, "Sexo" %>
      <%= form.select :sex, [['Masculino', 'masculino'], ['Femenino', 'femenino'], ['Otro', 'otro']] %>
    </div>

    <div class="field">
      <%= form.label :birth_date, "Fecha de Nacimiento" %>
      <%= form.date_field :birth_date, min: (Date.today - 100.years).strftime("%Y-%m-%d"), max: (Date.today).strftime("%Y-%m-%d"), required: true %>
    </div>

    <div class="field">
      <%= form.label :first_name, "Nombre" %>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name, "Apellido" %>
      <%= form.text_field :last_name %>
    </div>
  </div>

  <div class="field">
    <%= form.label :email, "Email" %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :address, "Dirección" %>
    <%= form.text_field :address %>
  </div>

  <div class="group_elements">

    <div class="field">
      <%= form.label :address_details, "Casa / Apartamento" %>
      <%= form.text_area :address_details %>
    </div>

    <div class="field">
      <%= form.label :country_id %>
      <%= form.collection_select :country_id, @countries, :id, :name, { prompt: 'Selecciona un país' }, { id: 'country_select' } %>
    </div>

    <div class="field">
      <%= form.label :department_id %>
      <%= form.collection_select :department_id, @departments, :id, :name, { prompt: 'Selecciona un departamento' }, { id: 'department_select' } %>
    </div>

    <div class="field">
      <%= form.label :city_id %>
      <%= form.collection_select :city_id, @cities, :id, :name, { prompt: 'Selecciona una ciudad' }, { id: 'city_select' } %>
    </div>

  </div>
  <div class="field">
    <%= form.label :information, "Información" %>
    <%= form.text_area :information %>
  </div>

  <div class="content-actions">
    <%= form.submit "Enviar", class: "btn-submit" %>
  </div>
<% end %>

</div>

app/views/contacts/show.html.erb
<h1>Detalles del Contacto</h1>

<p>
  <strong>Nombre:</strong>
  <%= @contact.first_name %>
</p>
<p>
  <strong>Apellido:</strong>
  <%= @contact.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>
<p>
  <strong>Dirección:</strong>
  <%= @contact.address %>
</p>
<p>
  <strong>Departamento:</strong>
  <%= @contact.department.name if @contact.department.present? %>
</p>
<p>
  <strong>Ciudad:</strong>
  <%= @contact.city.name if @contact.city.present? %>
</p>
<p>
  <strong>País:</strong>
  <%= @contact.country.name if @contact.country.present? %>
</p>

<p>
  <strong>Informacion:</strong>
  <%= @contact.information %>
</p>

<div  class="content-actions">
  <%= link_to 'Volver al listado', contacts_path, class: "btn btn-show" %>
  <%= link_to 'Editar', edit_contact_path(@contact), class: "btn btn-edit" %>
  <%= button_to "Eliminar", @contact, method: :delete, class: "btn btn-delete"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "G525 Contacto App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>